### ISSUE TITLE
Crypt19 not available anymore - so gem not installing

### ISSUE THREAD

**Issue by hqbeyers** [dougc84/carrierwave_securefile#8]
I encounter the follwoing error whilst installing the carrierwave_securefile gem:
To my Gemfile I added: gem 'carrierwave_securefile' and then I ran 'bundle' and the following error is shown:

```
Could not find gem 'crypt19 (= 1.2.1) ruby', which is required by gem
'carrierwave_securefile (>= 0) ruby', in any of the sources.Bundler could not
find compatible versions for gem "carrierwave":
In Gemfile:
carrierwave_securefile (>= 0) ruby depends on
carrierwave (~> 0.5.8) ruby
carrierwave (0.10.0)
```

I am using Rails 4.1.0 and ruby 2.1.2 but I can't think that is the problem here. 

I tried to install the crypt19-rb gem instead but the error does not go away.

**Comment by dougc84** [comment]
@hqbeyers - It looks like the `crypt19` gem is no longer published to rubygems.  `crypt19-rb` has nothing to do with the current implementation, so adding it to your `Gemfile` won't do anything.  You can see that is the case by referencing the gemspec.

You can get around it by requiring it manually in your Gemfile (not tested, should work):

``` ruby
gem "crypt19", github: "coupa/crypt19"
```

If that doesn't work, I'm not sure what else to tell you.  I haven't actively maintained this gem in an extended amount of time because I no longer use Carrierwave.
